// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAocQTBGx36fgUrpUpcPFN3iELZTzr2mYU',
    appId: '1:969570847406:web:3bc76540cc343ffba2fb3f',
    messagingSenderId: '969570847406',
    projectId: 'flutterapp-861cf',
    authDomain: 'flutterapp-861cf.firebaseapp.com',
    storageBucket: 'flutterapp-861cf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq2LX3L7BIMvnH0IM_nGwXY4ka8I8p2vg',
    appId: '1:969570847406:android:ad1bba66e0aeeb2da2fb3f',
    messagingSenderId: '969570847406',
    projectId: 'flutterapp-861cf',
    storageBucket: 'flutterapp-861cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH2n_8pm1-Fk3Wiq8T5UPbmmuKRvWl68s',
    appId: '1:969570847406:ios:8988ea2cb7af942da2fb3f',
    messagingSenderId: '969570847406',
    projectId: 'flutterapp-861cf',
    storageBucket: 'flutterapp-861cf.appspot.com',
    iosBundleId: 'com.example.myapplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAH2n_8pm1-Fk3Wiq8T5UPbmmuKRvWl68s',
    appId: '1:969570847406:ios:129f9e2f88fd972fa2fb3f',
    messagingSenderId: '969570847406',
    projectId: 'flutterapp-861cf',
    storageBucket: 'flutterapp-861cf.appspot.com',
    iosBundleId: 'com.example.myapplication.RunnerTests',
  );
}
